### ISSUE TITLE
MEP parties - at least 3 have greedy 4-line long party names

### ISSUE THREAD

**Issue by Rabscuttler** [civil-disobedience/votecheck#10]
...but the rest are mostly 1 or 2 lines. This either leaves lots of space on each grid item or overflows for the exceptions. 

I propose we trim the party name for those with very long ones (they seem to be doubled up names or hyphenated anyway). 

Noted: 
Mitro Repo
Liisa Jaakonsaari
Radvilė MORKŪNAITĖ-MIKULĖNIENĖ
Zuzana ROITHOVÁ
Slavi BINEV

**Comment by tttp** [comment]
@Rabscuttler long time no see . welcome
